UTC\StatsBundle\Entity\FileStats:
    type: entity
    table: null
    repositoryClass: UTC\StatsBundle\Entity\FileStatsRepository
    indexes:
        file_idx:
            columns: [filename]
            unique: true
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        filename:
            type: string
            length: 255
            unique: true
        isProcessed:
            type: boolean
            column: is_processed
        timestamp:
            type: datetimetz
            default: now
    uniqueConstraints:
        file_idx:
            columns: [filename]
            unique: true
    lifecycleCallbacks: {  }
