<?php

namespace UTC\StatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileStatsRepository extends EntityRepository
{
}
