utc_stats_homepage:
    pattern:  /
    defaults: { _controller: UTCStatsBundle:Default:index }

_players:
    pattern: /players
    defaults: { _controller: UTCStatsBundle:FrontEnd:players }


_teams:
    pattern: /teams
    defaults: { _controller: UTCStatsBundle:FrontEnd:teams }
