parameters:
#    utc_stats.example.class: UTC\StatsBundle\Example

services:
#    utc_stats.example:
#        class: %utc_stats.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
